//! Ed25519 signing of canonical bytes.
//!
//! - The signature is computed over the raw canonical bytes, not pretty JSON.
//! - The evidence bundle stores only:
//!     * operator_key_ref (string identifier)
//!     * public verification key (base64)
//!     * signature value (base64)
//! - Private key material is never written into any bundle, log, or report.

use crate::{Error, Result};
use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey, SECRET_KEY_LENGTH};
use rand::rngs::OsRng;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

/// A wrapped signing key plus its operator identifier.
///
/// `is_demo` marks a key generated by `generate-demo-key`. Production mode
/// refuses to use demo keys unless `--allow-demo-key` is set.
#[derive(Debug)]
pub struct OperatorKey {
    pub key_ref: String,
    pub is_demo: bool,
    signing: SigningKey,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignatureEnvelope {
    pub schema: String,
    pub record_id: String,
    pub plant_id: String,
    pub canonical_hash: String,
    pub signature: SignatureBlock,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignatureBlock {
    pub algorithm: String,
    pub operator_key_ref: String,
    pub public_key_b64: String,
    pub signature_value: String,
}

/// On-disk key file (demo or imported). Stored as JSON for transparency.
/// Holds the raw 32-byte Ed25519 secret seed, base64-encoded.
#[derive(Debug, Serialize, Deserialize)]
struct KeyFileV1 {
    schema: String,
    key_ref: String,
    algorithm: String,
    is_demo: bool,
    secret_seed_b64: String,
    public_key_b64: String,
}

impl OperatorKey {
    /// Generate a fresh demo key. Marked `is_demo = true`.
    pub fn generate_demo(key_ref: impl Into<String>) -> Self {
        let mut rng = OsRng;
        let signing = SigningKey::generate(&mut rng);
        OperatorKey {
            key_ref: key_ref.into(),
            is_demo: true,
            signing,
        }
    }

    pub fn public_key_b64(&self) -> String {
        B64.encode(self.signing.verifying_key().to_bytes())
    }

    pub fn sign_canonical(&self, canonical_bytes: &[u8]) -> Signature {
        self.signing.sign(canonical_bytes)
    }

    pub fn save_to_file(&self, path: &Path) -> Result<()> {
        let seed = self.signing.to_bytes();
        let kf = KeyFileV1 {
            schema: "ippan.pv.operator-key.v1".into(),
            key_ref: self.key_ref.clone(),
            algorithm: "ed25519".into(),
            is_demo: self.is_demo,
            secret_seed_b64: B64.encode(seed),
            public_key_b64: self.public_key_b64(),
        };
        let json = serde_json::to_string_pretty(&kf)?;
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent).map_err(|e| Error::io(parent, e))?;
            }
        }
        fs::write(path, json).map_err(|e| Error::io(path, e))?;
        Ok(())
    }

    pub fn load_from_file(path: &Path) -> Result<Self> {
        let bytes = fs::read(path).map_err(|e| Error::io(path, e))?;
        let kf: KeyFileV1 = serde_json::from_slice(&bytes)?;
        if kf.algorithm != "ed25519" {
            return Err(Error::Signature(format!(
                "unsupported key algorithm: {}",
                kf.algorithm
            )));
        }
        let seed_bytes = B64
            .decode(kf.secret_seed_b64.as_bytes())
            .map_err(|e| Error::Signature(format!("invalid base64 seed: {}", e)))?;
        if seed_bytes.len() != SECRET_KEY_LENGTH {
            return Err(Error::Signature(format!(
                "ed25519 seed must be {} bytes, got {}",
                SECRET_KEY_LENGTH,
                seed_bytes.len()
            )));
        }
        let mut seed = [0u8; SECRET_KEY_LENGTH];
        seed.copy_from_slice(&seed_bytes);
        let signing = SigningKey::from_bytes(&seed);
        Ok(OperatorKey {
            key_ref: kf.key_ref,
            is_demo: kf.is_demo,
            signing,
        })
    }
}

/// Build a signature envelope for the given canonical record.
pub fn build_envelope(
    key: &OperatorKey,
    record_id: &str,
    plant_id: &str,
    canonical_hash: &str,
    canonical_bytes: &[u8],
    created_at: &str,
) -> SignatureEnvelope {
    let sig = key.sign_canonical(canonical_bytes);
    SignatureEnvelope {
        schema: "ippan.pv.evidence-envelope.v1".into(),
        record_id: record_id.to_string(),
        plant_id: plant_id.to_string(),
        canonical_hash: canonical_hash.to_string(),
        signature: SignatureBlock {
            algorithm: "ed25519".into(),
            operator_key_ref: key.key_ref.clone(),
            public_key_b64: key.public_key_b64(),
            signature_value: B64.encode(sig.to_bytes()),
        },
        created_at: created_at.to_string(),
    }
}

/// Verify a signature envelope against the canonical bytes that produced it.
pub fn verify_envelope(env: &SignatureEnvelope, canonical_bytes: &[u8]) -> Result<()> {
    if env.signature.algorithm != "ed25519" {
        return Err(Error::Verification(format!(
            "unsupported algorithm: {}",
            env.signature.algorithm
        )));
    }
    let pk_bytes = B64
        .decode(env.signature.public_key_b64.as_bytes())
        .map_err(|e| Error::Verification(format!("invalid public key base64: {}", e)))?;
    if pk_bytes.len() != 32 {
        return Err(Error::Verification(format!(
            "public key must be 32 bytes, got {}",
            pk_bytes.len()
        )));
    }
    let mut pk_arr = [0u8; 32];
    pk_arr.copy_from_slice(&pk_bytes);
    let pk = VerifyingKey::from_bytes(&pk_arr)
        .map_err(|e| Error::Verification(format!("invalid public key: {}", e)))?;

    let sig_bytes = B64
        .decode(env.signature.signature_value.as_bytes())
        .map_err(|e| Error::Verification(format!("invalid signature base64: {}", e)))?;
    if sig_bytes.len() != 64 {
        return Err(Error::Verification(format!(
            "signature must be 64 bytes, got {}",
            sig_bytes.len()
        )));
    }
    let mut sig_arr = [0u8; 64];
    sig_arr.copy_from_slice(&sig_bytes);
    let sig = Signature::from_bytes(&sig_arr);

    pk.verify(canonical_bytes, &sig)
        .map_err(|e| Error::Verification(format!("ed25519 verify failed: {}", e)))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn sign_and_verify_round_trip() {
        let key = OperatorKey::generate_demo("key:test");
        let canonical = b"{\"x\":1}";
        let env = build_envelope(
            &key,
            "rec-1",
            "plant-1",
            "sha256:dummy",
            canonical,
            "2026-05-15T10:15:05Z",
        );
        assert!(verify_envelope(&env, canonical).is_ok());
    }

    #[test]
    fn modified_payload_fails_verification() {
        let key = OperatorKey::generate_demo("key:test");
        let canonical = b"{\"x\":1}";
        let env = build_envelope(
            &key,
            "rec-1",
            "plant-1",
            "sha256:dummy",
            canonical,
            "2026-05-15T10:15:05Z",
        );
        let tampered = b"{\"x\":2}";
        assert!(verify_envelope(&env, tampered).is_err());
    }

    #[test]
    fn key_round_trips_through_disk() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("k.json");
        let key = OperatorKey::generate_demo("key:test");
        let canonical = b"hello";
        let sig_before = key.sign_canonical(canonical);

        key.save_to_file(&path).unwrap();
        let loaded = OperatorKey::load_from_file(&path).unwrap();
        let sig_after = loaded.sign_canonical(canonical);

        assert_eq!(sig_before.to_bytes(), sig_after.to_bytes());
        assert!(loaded.is_demo);
        assert_eq!(loaded.key_ref, "key:test");
    }

    #[test]
    fn key_file_does_not_contain_secret_in_plaintext_form() {
        // Sanity: the key file holds the seed as base64 — this is fine for a
        // demo key. Real production keys should never be committed; the
        // .gitignore covers this. We only assert that the secret is not
        // logged or echoed elsewhere — see verify_envelope() / inspect.
        let dir = tempdir().unwrap();
        let path = dir.path().join("k.json");
        let key = OperatorKey::generate_demo("key:test");
        key.save_to_file(&path).unwrap();
        let txt = std::fs::read_to_string(&path).unwrap();
        assert!(txt.contains("secret_seed_b64"));
        assert!(txt.contains("\"is_demo\": true"));
    }
}
